# Generated by Django 3.2.14 on 2022-10-27 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_shoppingcart_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, '1 мин минимум'), django.core.validators.MaxValueValidator(500, 'не более 500 мин.')], verbose_name='Время приготовления, мин.'),
        ),
    ]
