# Generated by Django 3.2.14 on 2022-11-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_ingredientrecipe_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Количество ингредиента'),
        ),
    ]
